### ISSUE TITLE
Silverstripe 3

### ISSUE THREAD

**Issue by Firesphere** [titledk/silverstripe-projectmanagement#2]
Any update to 3 expected anytime soon?

**Comment by Firesphere** [comment]
Nevermind, I already asked.

**Comment by anselmdk** [comment]
@Firesphere actually I'm thinking of building an open source SilverStripe based CRM suite, which could also include a project management module, was discussing this with @Zauberfisch the other day, I've got some bits and pieces going, but the ode is a little old...
Don't expect anything any time soon, but I'm hoping for that to become my next bigger open source project.
